// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPXGE361bgh1Au0cwOESpCgOzDYpddqY',
    appId: '1:717372017853:web:828f9072aedcc8ab22bbd4',
    messagingSenderId: '717372017853',
    projectId: 'elsadeken-1',
    authDomain: 'elsadeken-1.firebaseapp.com',
    storageBucket: 'elsadeken-1.firebasestorage.app',
    measurementId: 'G-R3HW7HNY0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-j_CC1q3w0Jy1RfGM4oOItTbcsPKk5xU',
    appId: '1:717372017853:android:37d39f384c6b754a22bbd4',
    messagingSenderId: '717372017853',
    projectId: 'elsadeken-1',
    storageBucket: 'elsadeken-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9gmNJ63pNAhIMjQHV11TbIIDrI-1t9Q',
    appId: '1:717372017853:ios:813956ff4b8e9fa822bbd4',
    messagingSenderId: '717372017853',
    projectId: 'elsadeken-1',
    storageBucket: 'elsadeken-1.firebasestorage.app',
    iosBundleId: 'com.wessal.elsadeken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9gmNJ63pNAhIMjQHV11TbIIDrI-1t9Q',
    appId: '1:717372017853:ios:813956ff4b8e9fa822bbd4',
    messagingSenderId: '717372017853',
    projectId: 'elsadeken-1',
    storageBucket: 'elsadeken-1.firebasestorage.app',
    iosBundleId: 'com.wessal.elsadeken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPXGE361bgh1Au0cwOESpCgOzDYpddqY',
    appId: '1:717372017853:web:f61ea29886ba268822bbd4',
    messagingSenderId: '717372017853',
    projectId: 'elsadeken-1',
    authDomain: 'elsadeken-1.firebaseapp.com',
    storageBucket: 'elsadeken-1.firebasestorage.app',
    measurementId: 'G-7MNJCVCFKR',
  );
}
